version: "3.8"
services:

  swot-db:
    container_name: swot-db
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    stdin_open: false
    tty: false
    env_file: .env    
    ports:
       - ${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}
    volumes:
      - swot-db-data-volume:/var/lib/mysql
      - type: bind
        source: ${MYSQL_INIT_DB}
        target: /docker-entrypoint-initdb.d/initdb.sql
        read_only: true
    healthcheck:
        test: "mysql $${MYSQL_DATABASE} -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} -e 'SELECT 1;'"
        timeout: 20s
        retries: 10
    networks:
      - swot-net

  swot-app:
    container_name: swot-app
    image: eclipse-temurin:17
    command: java -jar /swot-app/swot-app.jar    
    stdin_open: false
    tty: false
    env_file: .env    
    ports:
      - ${SWOT_APP_PORT}:80
    volumes:
      - type: bind
        source: ${SWOT_APP_JAR}
        target: /swot-app/swot-app.jar
        read_only: true
    networks:
      - swot-net
    depends_on:
      swot-db:
        condition: service_healthy


networks:
  swot-net:

volumes:
  swot-db-data-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${MYSQL_DATAFILES_DIR}
