name: build-test-publish

on:
# Trigger workflow manually
 workflow_dispatch: 

jobs:

  build-test-publish-hello-project:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout this repository
      uses: actions/checkout@v3
 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2 
    
    - name: Test and build hello project with maven
      run: cd hello && mvn -B package --file pom.xml

    - name: Make staging directory
      run: mkdir staging
      
    - name: Copy the tested and built jar to staging  
      run: cp hello/target/*.jar staging
      
    - name: Upload the jar to GitHub packages
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging


#  publish-hello:
#      runs-on: ubuntu-latest
#      needs: [build-and-test-hello-project]
#      steps:
#        - uses: actions/checkout@v3
#        - uses: actions/setup-java@v3
#          with:
#            java-version: 17
#            distribution: 'temurin'
#            
#        - run: mkdir staging
#        - run: cd hello && mvn -B package --file pom.xml -DskipTests
#        - run: cp hello/target/*.jar staging
#        - uses: actions/upload-artifact@v3
#          with:
#            name: Package
#            path: staging

#  sftp-tools-runner:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      
#      - uses: mp30028/wf-temp/.github/actions/sftp-to-remote@main
#        with:
#          remote_username: ${{ secrets.REMOTE_USERNAME  }}
#          remote_host: ${{ secrets.REMOTE_SERVER  }}
#          remote_port: ${{ secrets.REMOTE_PORT  }}
#          remote_ssh_key: ${{ secrets.REMOTE_SSH_KEY  }}
#          local_filepath: ./runner
#          remote_filepath: ${{ vars.REMOTE_FILEPATH  }}/sopsage
#          
#  sftp-configs:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - uses: mp30028/sopsage/.github/actions/sftp-to-remote@main
#        with:
#          remote_username: ${{ secrets.REMOTE_USERNAME  }}
#          remote_host: ${{ secrets.REMOTE_SERVER  }}
#          remote_port: ${{ secrets.REMOTE_PORT  }}
#          remote_ssh_key: ${{ secrets.REMOTE_SSH_KEY  }}
#          local_filepath: ./configs
#          remote_filepath: ${{ vars.REMOTE_FILEPATH  }}/sopsage
#
#  sftp-tools:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - uses: mp30028/sopsage/.github/actions/sftp-to-remote@main
#        with:
#          remote_username: ${{ secrets.REMOTE_USERNAME  }}
#          remote_host: ${{ secrets.REMOTE_SERVER  }}
#          remote_port: ${{ secrets.REMOTE_PORT  }}
#          remote_ssh_key: ${{ secrets.REMOTE_SSH_KEY  }}
#          local_filepath: ./tools
#          remote_filepath: ${{ vars.REMOTE_FILEPATH  }}/sopsage
          
