name: keycloak-setup-on-remote

on:
 workflow_dispatch: 

jobs:

  push-keycloak-orchestration-artifacts-to-remote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make staging directory
        run: mkdir -p staging/keycloak

      - name: Copy keycloak setup to staging
        run: cp -r docker-setup/keycloak/* staging/keycloak

      - name: sftp staged artifacts to remote
        uses: mp30028/hello-workflow/.github/actions/sftp-to-remote@main
        with:
          remote_username: ${{ secrets.REMOTE_USERNAME  }}
          remote_host: ${{ secrets.REMOTE_SERVER  }}
          remote_port: ${{ secrets.REMOTE_PORT  }}
          remote_ssh_key: ${{ secrets.REMOTE_SSH_KEY  }}
          local_filepath: staging/keycloak
          remote_filepath: ${{ vars.REMOTE_FILEPATH  }}
          
  orchestrate-start-of-hello-app-on-remote:
      runs-on: ubuntu-latest
      needs: [push-keycloak-orchestration-artifacts-to-remote]
    
      steps:      
      - name: Execute remote command to start or restart containers
        uses: mp30028/hello-workflow/.github/actions/execute-remote-command@main
        with:
          remote_username: ${{ secrets.REMOTE_USERNAME  }}
          remote_host: ${{ secrets.REMOTE_SERVER  }}
          remote_port: ${{ secrets.REMOTE_PORT  }}
          remote_ssh_key: ${{ secrets.REMOTE_SSH_KEY  }}
          remote_cmd: cd ${{ vars.REMOTE_FILEPATH  }}/keycloak; docker compose down; docker compose up -d;